Add ctx
prefapp/action-deployment-dispatch pull request #4
Opened 2021-07-22 15:56 UTC by frmadem

Add master branch and current branch to context.

2021-07-22 16:59 UTC, alambike commented on index.js
> +    master_branch: github.context.payload.repository.master_branch,
@frmadem what is `master_branch`?

2021-07-22 17:01 UTC, alambike commented on index.js
> +    master_branch: github.context.payload.repository.master_branch,
Okey, I see it: 


master_branch | string | The name of the repository's default branch (usually main).
-- | -- | --

2021-07-22 17:30 UTC, alambike requested changes

2021-07-22 17:30 UTC, alambike commented on index.js
>      current_branch: github.context.ref.replace("refs/heads/", ""),
This entry should be removed and calculated in the method where necessary, because the context changes based on the trigger
For example, for the event of [pull_request[labeled]](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request) it will have to be removed from `context.head.ref` and you do not need to remove `ref/heads` string:

![image](https://user-images.githubusercontent.com/1025564/126682787-d7def218-d7cd-481e-ad8b-7b25b0c12218.png)

2021-07-22 17:37 UTC, frmadem commented on index.js
>      current_branch: github.context.ref.replace("refs/heads/", ""),
@alambike so we could calculate it on the GitControl class/method right?

2021-07-23 08:55 UTC, alambike approved these changes

2021-07-23 08:57 UTC, merged